### ISSUE TITLE
Theme Seemingly Lacks 'metadata.desktop' File

### ISSUE THREAD

**Issue by GreyAsh** [michaldybczak/MaiaTransparent-plasma-theme#3] opened 2021-04-30 23:46 UTC
Hai,
Many thanks for taking the time to make this available to us.

The theme only b/c available after I slightly modified the metadata.desktop file from the maia plasma theme (and copied and pasted it into the MaiaTransparent directory).

Cheers.

**Comment by michaldybczak** [comment] 2021-05-01 10:51
Thanks for noticing. I realized, I misplaced somehow the metafile when moving to github. I published originally the theme on pling and not so long ago published it on github upon a request, and it looks I somehow forgot to copy metafile. It is however present in the download files on pling. I'll update the github. Can you post the content of that file, so I could cross-check it with the one I have? If needed, I include your changes.

Also, what do you mean by "b/c available"? I'm not familiar with that notion. Do you mean, that the theme wasn't visible in the settings menu in Plasma? If you used the github version without metafile then this would be to be expected.

**Comment by michaldybczak** [comment] 2021-05-02 08:43
Since I added the missing metadata.desktop and updated svgz files (version 4.1), I'm assuming the issue is fixed. If this does not help, let me know, and I reopen the case.

**Closed as completed by michaldybczak** 2021-05-02 08:43 UTC
